# create your drupal and postgres config here, based off the last assignment
services:
  drupal:
    image: drupal:9
    build: .
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=mypasswd
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=mariadb 
      - MARIADB_PASSWORD=mypasswd
    volumes:
      - drupal-data:/var/lib/mysql
volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
